# Generated by Django 5.1.2 on 2024-12-18 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя столика')),
                ('capacity', models.PositiveIntegerField(verbose_name='Количество человек')),
                ('table_type', models.CharField(choices=[('regular', 'Обычный'), ('vip', 'VIP'), ('outdoor', 'На улице')], max_length=20, verbose_name='Тип столика')),
                ('x_coord', models.PositiveIntegerField(default=0, verbose_name='X-позиция')),
                ('y_coord', models.PositiveIntegerField(default=0, verbose_name='Y-позиция')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time_from', models.TimeField(verbose_name='Время от')),
                ('time_to', models.TimeField(verbose_name='Время до')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Подтвержден ли заказ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.table', verbose_name='Столик')),
            ],
        ),
    ]
