# Generated by Django 5.1.4 on 2024-12-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guests_count',
            field=models.IntegerField(db_default=1, verbose_name='Количество гостей'),
        ),
    ]
