# Generated by Django 5.1.4 on 2024-12-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_guests_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guests_count',
            field=models.IntegerField(default=1, verbose_name='Количество гостей'),
        ),
    ]
